name: Dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: "A direct download link for the firmware file that is to be dumped."
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TZ: Asia/Kolkata

jobs:
  Firmware-Dump:
    runs-on: ubuntu-22.04

    steps:
      - name: Free up some storage space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Clone the dumper script
        run: |
          git clone --depth 1 -b main https://github.com/prathamdubey2005-alt/firmware-dumper-script.git dumper

      - name: Set up all of the SSH keys
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa "${{ secrets.GITLABINSTANCE }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSHKEYPRIVATE }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSHKEYPUBLIC }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-agent -s
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Install all of the requirements
        working-directory: dumper
        run: |
          bash setup.sh

      - name: Dump the firmware
        working-directory: dumper
        run: |
          export PUSH_TO_GITLAB=true
          echo "${{ secrets.GITLABINSTANCE }}" > .gitlab_instance
          echo "${{ secrets.GITLABGROUP }}" > .gitlab_group
          echo "${{ secrets.GITLABTOKEN }}" > .gitlab_token
          echo "${{ secrets.TGCHAT }}" > .tg_chat
          echo "${{ secrets.TGTOKEN }}" > .tg_token
          bash dumper.sh $LINK
